name: backend build & deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Run tests with Gradle
      working-directory: ./web-app
      run: ./gradlew test
    
    - name: Build Spring Boot JAR with Gradle
      working-directory: ./worklifeintegration-server
      run: ./gradlew bootJar

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Deploy to AWS Elastic Beanstalk
      urss: einaregilsson/beanstalk-deploy@v21
      working-directory: ./worklifeintegration-server
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: worklifeintegration
        environment_name: Worklifeintegration-env
        version_label: ${{ steps.date.outputs.date }}
        region: eu-central-1
        deployment_package: build/libs/worklifeintegration-server-0.0.1-SNAPSHOT.jar
